---
title: "making occupancy models plots"
format: html
editor_options: 
  chunk_output_type: console
---

```{r load-packages}
library(brms)
library(ggdist)
library(ggtext)
library(posterior)
library(tidyverse)
library(here)
```


```{r get-info}
species_groups <- read_csv(here("data", "DuneFront_WP4.2_species_groups.csv"))

tab <- tibble(
  filename = list.files(here("output", "occupancy_models"), pattern=".RDS$"),
  filepath = list.files(here("output", "occupancy_models"), full.names = TRUE, pattern=".RDS$")
) |> 
  filter(!str_detect(filename,"Carpobrotus_complex"))
```

```{r load-posterior-params}
tab <- tab |>
  mutate(
    posteriors = map(
      .x = filepath,
      .f = function(.x) {
        readRDS(.x) |>
          as_draws_df() |>
          select(starts_with("b_"))
      }
    )
  )
# there will be warnings (due to dropping Bayesian-related metadata with select()), but they are OK
```


```{r clean-posteriors}
tab <- tab |>
  mutate(
    tab_det = map(
      .x = posteriors,
      .f = function(.x) {
        select(.x, !starts_with("b_occ_")) |>
          mutate(
            `1` = plogis(b_Intercept),
            `2 or 3` = plogis(b_Intercept + b_ll2_3),
            `4 or more` = plogis(b_Intercept + b_ll4_more)
          ) |>
          select(
            c(
              `1`,
              `2 or 3`,
              `4 or more`
            )
          ) |>
          pivot_longer(everything())
      }
    ),
    tab_occ = map(
      .x = posteriors,
      .f = function(.x) {
        select(.x, starts_with("b_occ_")) |>
          select(-b_occ_Intercept) |>
          pivot_longer(everything()) |>
          mutate(name = case_when(
            name == "b_occ_urban02_DUC" ~ "Dense Urban Cluster",
            name == "b_occ_urban03_UC" ~ "Urban Centre"
          ))
      }
    )
  ) |>
  mutate(species = str_remove(filename, "occ_") |>
    str_remove("_multiyear.RDS")) |>
  left_join(species_groups) |>
  mutate(species = str_replace(species, "_", " ")) |>
  mutate(species = paste0("*", species, "*")) |>
  select(species, group, tab_det, tab_occ)
```

```{r plot-urbanization-effect}
select(tab, species, group, tab_occ) |>
  unnest(cols = c(tab_occ)) |>
  mutate(name = fct_rev(name), species = fct_rev(species)) |>
  mutate(name = fct_rev(name)) |>
  rename(`GHSL SMOD` = "name") |>
  ggplot() +
  stat_pointinterval(aes(value, species, col = `GHSL SMOD`),
    position = position_dodge(width = 0.3), .width = c(0, 0.95)
  ) +
  geom_vline(xintercept = 0, linetype = 2) +
  scale_y_discrete("") +
  scale_x_continuous("Effect of urbanization (difference vs. rural on logit scale)", lim = c(-5, 5)) +
  theme_bw() +
  theme(
    legend.position = "bottom", axis.text.y = element_markdown(),
    strip.text.y.right = element_text(angle = 0)
  ) +
  facet_grid(
    rows = vars(group),
    scales = "free_y", space = "free"
  )
```

```{r plot-detection}
select(tab, species, group, tab_det) |>
  unnest(cols = c(tab_det)) |>
  mutate(species = fct_rev(species)) |>
  rename(`list length` = "name") |>
  ggplot() +
  stat_pointinterval(aes(value, species), .width = c(0, 0.95)) +
  scale_x_continuous("detection probability", lim = c(0, 0.5)) +
  scale_y_discrete("") +
  theme_bw() +
  theme(
    legend.position = "none", axis.text.y = element_markdown(),
    strip.text.y.right = element_text(angle = 0)
  ) +
  facet_grid(
    cols = vars(paste("list length:", `list length`)), rows = vars(group),
    scales = "free_y", space = "free"
  )
```
